config/routes.rb
Rails.application.routes.draw do
  get 'artistas/walter', to: 'artistas#walter'

  get 'artistas/luis', to: 'artistas#luis'

  get 'artistas/susana', to: 'artistas#susana'

  get 'artistas/juan', to: 'artistas#juan'

  get 'artistas/angel', to: 'artistas#angel'

  get 'artistas/jesus', to: 'artistas#jesus'

  get 'artistas/jani', to: 'artistas#jani'

  get 'artistas/hugo', to: 'artistas#hugo'

  get 'artistas/eugenio', to: 'artistas#eugenio'

  get 'artistas/marco', to: 'artistas#marco'

  get 'pages/home'

  get 'pages/proyecto',to: 'pages#proyecto'

  get 'pages/photos',to: 'pages#photos'

  get 'pages/objetivos'

  get 'pages/evento', to:'pages#evento'

  get 'pages/artistas', to: 'pages#artistas'

   get 'pages/contact', to: 'pages#contact'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artistas_controller.rb
class ArtistasController < ApplicationController
  def walter
  end

  def luis
  end

  def susana
  end

  def juan
  end

  def angel
  end

  def jesus
  end

  def jani
  end

  def hugo
  end

  def eugenio
  end

  def marco
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def proyecto
  end

  def objetivos
  end

  def evento
  end

  def artistas
  end

  def photos
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/artistas/angel.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Ángel Ariel Núñez</h2>
        <h4>@_angelariel</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        De 27 años, tomar fotos es algo que empezó a hacer desde muy pequeño con
        las cámaras tipo “aficionado” de su papá; siempre fue algo con lo que convivió; rollos por aquí y por allá eran parte de sus juguetes favoritos y a medida que fue creciendo se hizo más presente en su vida.
        </p>
        <p>
        La fotografía es algo que lo libera,le hace sentir paz y tranquilidad;salir con su móvil o una cámara en mano le permite capturar momentos importantes, irrepetibleso simplemente únicos; Instagram sin duda representa el lugar perfecto para llegar a todas esas personas que aprecian de una manera u otra el arte de capturar momentos.
        </p>
        <p>
        El estilo que lo define sin duda es “Nature and Landscape” le encanta el verde y el azul de nuestro planeta y con estos estilos es fácil de plasmar esos colores
        Sueña con llegar a más personas que aprecien sus fotos, que puedan ver en él un ejemplo; de que lo que
        te propongas puedes lograrlo! no importa cuán alta se vea una cima, puedes llegar a ella y ver el mundo a tus pies! y; este anhelo y el de muchos otros estará un poquito más cerca
        a través de este tipo de apoyo hacia los instagramers, eso es lo que me motiva y mueve a participar de esta exhibición.
        </p>
        </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('angel.png')%>
        <br>
        <a href="https://www.instagram.com/_angelariel/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/eugenio.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Eugenio Igoa</h2>
        <h4>@eigoae</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        27 años, español. Tomar fotos es una bonita manera de ir documentando recuerdos.
        </p>
        <p>
       Comenzó a hacerlo en cuanto tuvo un smartphone con buenas capacidades fotográficas. Instagram fue clave en el desarrollo de esta afición, donde ha encontrado inspiración y ha compartido experiencias con gente de todo el mundo. Se identifica con el minimalismo, le gustan las composiciones sencillas y le pone mucha atención a la posición de los elementos, buscando el equilibrio geométrico. Le gusta controlar la escena, aunque en ocasiones se permite ciertas concesiones (cada vez más). Poco a poco, va entendiendo que la fotografía no debe ser tan rígida y que la magia de la misma no está determinada por ninguna regla.
        </p>

      </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('eugenio.png')%>
        <br>
        <a href="https://www.instagram.com/eigoae/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/hugo.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Hugo González</h2>
        <h4>@hugo.jpeg</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        Desde pequeño demostró interés por explorar su creatividad a través de diferentes medios.
        </p>
        <p>
       Se muda con su familia a Panamá, donde junto a él crece su interés por la arquitectura y la fotografía. En su trabajo fotográfico intenta plasmar las distintas interacciones que se dan cotidianamente entre componentes arquitectónicos, la naturaleza y los seres vivos. Sus fotografías contienen elementos específicos cuyas composiciones lineales reflejan su formación en arquitectura. Desde su creación, Instagram ha sido una herramienta fundamental para dar a conocer su perspectiva visual de Panamá y el mundo; y con en esta exhibición espera seguir compartiendo su visión.
        </p>

      </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('hugo.png')%>
        <br>
        <a href="https://www.instagram.com/hugo.jpeg/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/jani.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Jani Aguilar</h2>
        <h4>@janie_aguilarr</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        Tiene 24 años, desde pequeña le llamó la atención todo lo relacionado al arte en todas su facetas como el dibujo, pintura, diseño de moda, tallados con madera y todo tipo de creaciones.
        </p>
        <p>
        La fotografía para ella es una pintura de la realidad, el cual busca transmitir siempre un sentir, que otros también vean la tierra como parte de ellos mismos. Sembrar conciencia sobre su importancia, ya que somos naturaleza.
        </p>

      </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('janie.png')%>
        <br>
        <a href="https://www.instagram.com/janie_aguilarr/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/jesus.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Jesús Antonio Hernández</h2>
        <h4>@_antoh</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        Tiene 21 años de edad. Una de sus motivaciones es sin duda el momento en el que las personas le comparten cuan maravillados están por sus foto- grafías, donde muestra una conexión con la naturaleza y los escenarios.
        </p>
        <p>
        cuando le comentan, le escriben por mensaje privado para pedirle uno que otro consejo y le animan a seguir con lo que hace; porque de alguna u otra manera representa una esperanza de impulso para ellos a descubrir, eso es lo que realmente le motiva ser fotógrafo.
        </p>
        <p>
        Instagram significa todo, esta red social donde encuentras maravillas, donde te conectas con el mundo, mediante fotos y vídeos, donde encuentras a personas con sus mismo gusto y que va de fotos de retratos a paisajes increíbles, no encontraríamos límites para expresar cómo se ve el mundo. Es la plataforma que le ha llevado su trabajo a más ojos y rincones.
        </p>
      </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('jesus.png')%>
        <br>
        <a href="https://www.instagram.com/_antoh/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/juan.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Juan De Dios Castillo</h2>
        <h4>@juandediosc</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        Juan De Dios, de 32 años, es fotógrafo profesional, diseñador gráfico y buzo avanzado. El tiempo le ha permitido reunir experiencia en todas las facetas del arte y ha sido parte de valiosos equipos que desarrollan proyectos de alto impacto en Panamá y toda la región llegando incluso a liderarlos como director de arte y creativo.
        </p>
        <p>
        Hace algunos años descubrió que se siente muy cómodo con su actual estilo, la fotografía documental. Disfruta poder contar historias a través de su trabajo y tiene una gran atracción por la naturaleza, confiesa que es de las fotografías que más le gusta hacer, su belleza obliga sin duda una reverencia.
        </p>
        <p>
        Cree que su trabajo podría contri- buir a la exposición evidenciando que Panamá tiene lugares increíbles cree fielmente en que todos podemos disfrutar de lo hermoso que la naturaleza nos regala y el poder inspi- rar a otros a través de su trabajo es la motivación más relevante para ser parte de esta exposición.
        </p>
        </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('juan.png')%>
        <br>
        <a href="https://www.instagram.com/juandediosc/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/artistas/luis.html.erb
<%= render 'shared/navbar' %>
    <div class="container">
      <div class="nombre">
        <h2>Luis Zamora</h2>
        <h4>@luis_zamorav</h4>
        <hr>
      </div>
    </div>
    <div class="container">
      <div class="row profile">
        <div class="col-xs-12 col-sm-6">
        <p>
        Fotógrafo aventurero, panameño con 25 años de edad, amante de la naturaleza y adicto a las cascadas.
        </p>
        <p>
        Más que solo un paisaje bonito lo que quiere transmitir a través de sus fotos es esa conexión entre el hombre y la naturaleza, ese amor con el que estamos todos conectados para que la cuidemos y que al ver la foto se transmita el deseo de estar allí llenándote de esa energía que sólo se siente al estar en contacto con la Madre Tierra.</p>
        <p>
        Le gusta instagram porque es una herramienta para dar a conocer rápidamente, sea lo que sea que hagas. Es interesante porque nos hace dar cuenta que no hay fronteras para conectar con personas que comparten tus gustos y pasiones e inspirarte aún más a seguir creando.
        </p>
        <p>
        En cuanto a su estilo, podría parecer que le gusta la oscuridad pero en realidad le gusta es el contraste entre la luz y las sombras, le gusta que el negro se vea tal cual, eso hace que sobresalga lo que está más iluminado en su composición, los tonos cálidos y los verdes son bastante comunes en su fotografía. Le motiva ser parte de la exhibición para inspirar a más personas a que sigan sus pasiones y nos inspiren a todos a seguir las nuestras.
        </p>
        </div>
        <div class="col-xs-12 col-sm-6 text-center gallery">
        <%= image_tag('luis.png')%>
        <br>
        <a href="https://www.instagram.com/luis_zamorav/"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Panamá Instantánea</title>
  <%= render 'application/favicon' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=ABeeZee|Averia+Sans+Libre|Sniglet" rel="stylesheet">
</head>
<body class="Site">
  <main class="Site-content">
    <%= yield %>
  </main>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/pages/artistas.html.erb
<%= render 'shared/navbar' %>
  <div class="container text-center">
    <div class="title">
      <h3><strong>ARTISTAS</strong></h3>
      <hr>
    </div>
  </div>
  <div class="container padded">
    <div class="row artistas">
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_walter_path do %>
        <%= image_tag('walter2.png')%>
        <h5>Walter Hurtado</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_luis_path do %>
        <%= image_tag('luis.png')%>
        <h5>Luis Zamora</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_susana_path do %>
        <%= image_tag('susana2.png')%>
        <h5>Susana Aramburú</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_juan_path do %>
        <%= image_tag('juan2.png')%>
        <h5>Juan De Dios Castillo</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_angel_path do %>
        <%= image_tag('angel.png')%>
        <h5>Ángel Ariel Núñez</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_jesus_path do %>
        <%= image_tag('jesus.png')%>
        <h5>Jesús Antonio Hernández</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_jani_path do %>
        <%= image_tag('jani2.png')%>
        <h5>Jani Aguilar</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_hugo_path do %>
        <%= image_tag('hugo2.png')%>
        <h5>Hugo González</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_eugenio_path do %>
        <%= image_tag('eugenio.png')%>
        <h5>Eugenio Igoa</h5>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-4 text-center">
        <%= link_to artistas_marco_path do %>
        <%= image_tag('marco2.png')%>
        <h5>Marco Chen</h5>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <br>
</div>
</div>

app/views/pages/evento.html.erb
<%= render 'shared/navbar' %>
<!-- <div style="background-image: linear-gradient(-225deg, rgba(280,20,0,0.6) 0%, rgba(250,0,0,0.7) 50%), url('<%= image_path('cholito.png')%>'); height: 50vh;">
</div> -->
<div class="evento">
  <div>
    <h3 class ="pad"><strong>EXPOSICIÓN</strong></h3>
    <ul class="list-unstyled pad">
      <a href="https://www.google.com.pa/maps/place/Hilton+Panam%C3%A1/@8.9758587,-79.5246984,17z/data=!3m1!4b1!4m5!3m4!1s0x8faca8e718730dc7:0xa0b50e752724620f!8m2!3d8.9758587!4d-79.5225097?hl=en
      ">
      <li><i class="fa fa-map-marker symbols2" aria-hidden="true"></i></li>
    </a>
    <br>
    <li><p><strong>LUGAR:</strong> HOTEL HILTON PANAMÁ AVENIDA BALBOA<br> GALERIA ABIERTA BY PUNTO BOHEMIO, LOBBY 2</p></li>
    <br>
    <li><i class="fa fa-calendar symbols2" aria-hidden="true"></i></li>
    <br>
    <li><p><strong>EVENTO INAUGURAL:</strong> 19 DE SEPTIEMBRE</p></li>
    <li><p><strong>HORA: </strong> 7:00 PM</p></li>
    <p><strong>EXHIBICIÓN: </strong>SEPTIEMBRE 19 - OCTUBRE 14</p></li>
  </ul>
   <%= link_to "Ver Artistas", pages_artistas_path, class: "btn btn-danger"%>
   <br>
   <br>
   <%= link_to "Galería", pages_photos_path, class: "btn btn-danger"%>
  <div class="container">
    <div class="col-xs-12 padded" style="text-align: center;">
      <p>En esta primera edición, presentamos 10 artistas, que nos invitan a ver lo   cotidiano con ojos diferentes. La herramienta de los artistas en Panamá Instantánea para compartir  y generar sus fotografías en Instagram. Esta plataforma se convierte en galería móvil para estos artistas emergentes, que muestran de forma instantánea perspectivas plasmadas en imágenes. De ahí, el nombre de este proyecto.
        <br>
        <br>
        Esta exhibición se realiza en el nuevo concepto de Galería Abierta de Punto Bohemio en el Hotel Hilton, la cual consiste en un espacio gratuito, abierto a todo público. Por un tiempo específico se transforma en un centro de exhibición, promoción, apreciación y venta de arte.  Creado con la intención de lograr la interacción inesperada, entre el público y las obras.

        <br>
        <br>
        Vén, conoce y apoya al artista emergente. Inspirate a compartir.
      </p>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<%= render 'shared/banner' %>
<div class="white proyecto">
  <div class="container text-center">
    <h3> <strong>EL PROYECTO</strong></h3>
    <div class="container">
      <div class="col-xs-12  col-sm-8 col-sm-offset-2">
        <h5>“LA FOTOGRAFÍA, HERRAMIENTA VISUAL QUE DESPIERTA EL INTERÉS POR CONOCER Y CREAR NUEVAS EXPERIENCIAS”</h5>
      </div>
    </div>
    <br>
   <p style="text-align: center;"> Panamá Instantánea nace como una iniciativa de un grupo de jóvenes radicados en Panamá,<br> que comparten una misma afición por la fotografía e Instagram.
      <br>
      <br>
      En esta edición, forma parte del circuito fotográfico Foto Septiembre, impulsado por el MAC.
    </p>
    <div class="padded">
      <%= link_to "Ver más", pages_proyecto_path, class: "btn btn-danger"%>
    </div>
      <br>
      <p style="text-align: center;">
        2017, primera edición: Formó parte del circuito fotográfico Foto Septiembre, impulsado y creado por el MAC Panamá (Museo de Arte Contemporáneo)  <br>
        De octubre hasta el mes de diciembre del 2017, se transforma en una exhibición itinerante,
        recorriendo diversos puntos de la ciudad de Panamá.
      </p>
      <div class="padded">
      <%= link_to "Se parte, apoya y dona", pages_contact_path, class: "btn btn-danger"%>
    </div>
  </div>
  <div class="row text-center" >
    <br>
    <div class="col-xs-12 col-md-3">
      <%= image_tag('logopunto.png')%>
    </div>
    <div class="col-xs-12 col-md-2">
      <%= image_tag('pb.png')%>
    </div>
    <div class="col-xs-12 col-md-2">
      <%= image_tag('mac.png')%>
    </div>
    <div class="col-xs-12 col-md-2">
      <%= image_tag('af.png')%>
    </div>
    <div class="col-xs-12 col-md-3">
      <%= image_tag('hilton2.png')%>
    </div>

  </div>
  <br>
  <br>
</div>

<div class="expocicion" style="background-image: linear-gradient(-225deg, rgba(280,20,0,0.6) 0%, rgba(250,0,0,0.7) 50%), url('<%= image_path('objetivos.png')%>');background-position: center;">
  <div class= "padded">
    <h3><strong>EXPOSICIÓN</strong></h3>
    <ul class="list-unstyled">

      <li><i class="fa fa-camera-retro symbols" aria-hidden="true"></i></li>

      <br>
      <li><p>Galeria online de Panamá Instantánea.</p></li>
      <br>
      <div class="col-xs-12">
        <%= link_to "Ver fotografías en exhibición", pages_photos_path, class: "btn btn-expo"%>
      </div>
    </ul>
    <br>
    <br>
    <br>
    <div class="col-xs-12 col-sm-6">
      <%= link_to "Ver Artistas", pages_artistas_path, class: "btn btn-expo"%>
    </div>
    <div class="col-xs-12 col-sm-6 pad">
      <%= link_to "Más Sobre la Expo", pages_evento_path, class: "btn btn-expo"%>
    </div>
  </div>
</div>
<br>
<br>

<br>
<div class="hidden-xs hidden-sm">
  <div class="white">
    <div class="container">
      <div class="row fundacion text-center">
        <div class="col-xs-12">
          <%= image_tag('fundacion.png')%>
        </div>
      </div>
      <div class="wrappper-background">
          <div class="col-xs-12" style="text-align: center;">
            <p>Fundada en el 2012 por un colectivo de profesionales y artistas. <br>Apoya y promueve los diversos sectores artísticos en Panamá; dando soporte <br> a la formación y profesionalización de artistas emergentes, creando nexos entre el público y la cultural.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="hidden-md hidden-lg">
  <div class="white">
    <div class="container">
      <div class="row fundacion text-center">
        <div class="col-xs-12">
          <%= image_tag('logopunto.png')%>
        </div>
        <div class="col-xs-12" style="text-align: center;">
          <p>Fundada en el 2012 por un colectivo de profesionales y artistas.
            <br>Apoya y promueve los diversos sectores artísticos en Panamá; dando soporte a la formación y profesionalización de artistas emergentes, creando nexos entre el público y la cultural.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>

app/views/pages/proyecto.html.erb
<%= render 'shared/navbar' %>
<div class="white">
  <div class="container text-center">
    <div class="size">
      <%= image_tag "pismallred.png"%>
    </div>
    <div class="proyecto">
      <h3> <strong>PANAMÁ INSTANTÁNEA</strong></h3>
      <hr>
      <p style="text-align: center;"> PANAMÁ INSTANTÁNEA es un grupo de jóvenes radicados en Panamá que comparten una misma afición por la fotografía e Instagram. El grupo ha sido formado a través de las redes sociales, donde cada uno de nosotros comparte las experiencias y momentos vividos en Panamá a través de fotografías que, a lo largo del tiempo, han ido ganando reconocimiento de otros usuarios locales por tener un estilo personal diferenciador.
      </p>
      <br>
      <p style="text-align: center;">
      Los integrantes del grupo compartimos una misma visión sobre el entorno que nos rodea lo apreciamos con otros ojos y lo retratamos para el mundo, procurando sacar lo mejor de él. Amamos a Panamá y estamos seguros de que este proyecto inspirará a los asistentes ver lo cotidiano con ojos diferentes.</p>
      <br>
      <p style="text-align: center;">
        2017, primera edición: Formó parte del circuito fotográfico Foto Septiembre, impulsado y creado por el MAC Panamá (Museo de Arte Contemporáneo)  <br>
        De octubre hasta el mes de diciembre del 2017, se transforma en una exhibición itinerante,
        recorriendo diversos puntos de la ciudad de Panamá.
      </p>
      <div class="padded">
      <%= link_to "Se parte, apoya y dona", pages_contact_path, class: "btn btn-danger"%>
    </div>
    </div>
  </div>
  <br>
  <br>
  <div class="text-center">
    <div class="expocicion" style="background-image: linear-gradient(-225deg, rgba(280,20,0,0.6) 0%, rgba(250,0,0,0.7) 50%), url('<%= image_path('cholito.png')%>'); background-position: center;">
      <h3><strong>OBJETIVOS</strong></h3>
      <br>
      <ul class="list-unstyled">
        <li>· Fomentar y dar visibilidad al trabajo fotográfico digital y nuevas tecnologías.
        </li>
        <br>
        <li>· Generar espacios de diálogos y reflexión.</li>
        <br>
        <li>· Impulsar el turismo local, dando a conocer a nuestro país desde otras perspectivas.</li>
        <br>
        <li>· Crear banco de imágenes abiertas del país.</li>
        <br>
        <li>· Impulsar la creación de una red milenial con visión artística e influencia digital.</li>
      </ul>
    </div>
  </div>
  <br>

  <br>
  <div class="proyecto text-center">
    <div class="text-center ">
      <p>Patrocinadores y Aliados 2017</p>
      <div class="row text-center" >
        <br>
        <div class="col-xs-12 col-md-3">
          <%= image_tag('logopunto.png')%>
        </div>
        <div class="col-xs-12 col-md-2">
          <%= image_tag('pb.png')%>
        </div>
        <div class="col-xs-12 col-md-2">
          <%= image_tag('mac.png')%>
        </div>
        <div class="col-xs-12 col-md-2">
          <%= image_tag('af.png')%>
        </div>
        <div class="col-xs-12 col-md-3">
          <%= image_tag('hilton2.png')%>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "pismall.png" %>
  <% end %>
  <div class="dropdown ">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
     <li> <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
      <li> <%= link_to "Proyecto", pages_proyecto_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
      <li> <%= link_to "Artistas", pages_artistas_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
      <li> <%= link_to "Evento", pages_evento_path, class: "navbar-wagon-item navbar-wagon-link"%> </li>
    </ul>
  </div>

</div>